fix: enableCSPNonces behavior
fastify/fastify-helmet pull request #124
Opened 2021-03-18 02:53 UTC by climba03003

Resolves: #118
Resolves: #119
Resolves: #120

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2021-03-18 02:55 UTC, climba03003 commented
@katywings Can you review this PR? Is it fixed with all the three issue you raised?

2021-03-18 08:40 UTC, mcollina requested changes

2021-03-18 08:40 UTC, mcollina commented on test.js
> +  }
the try-catch wrapper is not needed, remove it

2021-03-18 08:40 UTC, mcollina commented on test.js
> +  }
remove the try-catch wrapper

2021-03-18 11:13 UTC, mcollina approved these changes
lgtm

2021-03-19 12:18 UTC, katywings approved these changes
Thank you so much for this 😍! Lookin great 🤩

2021-03-19 14:45 UTC, merged